name: Publish Python Package to PyPI

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on tags like v0.1.0, v1.2.3, etc.

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      # Grant id-token write permission for trusted publishing
      id-token: write
    steps:
    - uses: actions/checkout@v4
      # Fetch all history for all tags and branches for setuptools-scm
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: python -m build

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
